import type { Metadata } from "next";
import {
  Jomhuria,
  Luxurious_Roman,
  Almendra,
  Poppins,
  Playfair_Display,
  Raleway,
  Lora,
  Montserrat,
  Inter,
  DM_Serif_Display,
  Manrope,
  Outfit,
  Merriweather,
} from 'next/font/google';
import "./globals.css";
import {FaWhatsapp} from 'react-icons/fa';
import Footer from "./components/footer";
import Navbar from "./components/navigation";


const jomhuria = Jomhuria({ subsets: ['latin'], weight: '400', variable: '--font-jomhuria' });
const luxurious = Luxurious_Roman({ subsets: ['latin'], weight: '400', variable: '--font-luxurious' });
const almendra = Almendra({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-almendra' });

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'], variable: '--font-poppins' });
const playfair = Playfair_Display({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-playfair' });
const raleway = Raleway({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-raleway' });
const lora = Lora({ subsets: ['latin'], weight: ['400', '600'], variable: '--font-lora' });
const montserrat = Montserrat({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-montserrat' });
const inter = Inter({ subsets: ['latin'], weight: ['400', '600'], variable: '--font-inter' });
const dmserif = DM_Serif_Display({ subsets: ['latin'], weight: '400', variable: '--font-dmserif' });
const manrope = Manrope({ subsets: ['latin'], weight: ['400', '600'], variable: '--font-manrope' });
const outfit = Outfit({ subsets: ['latin'], weight: ['400', '600'], variable: '--font-outfit' });
const merriweather = Merriweather({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-merriweather' });

export const metadata: Metadata = {
  title: "IMSS-Infintive Marketing Service and Solution",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png',}
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
        ${jomhuria.variable} ${luxurious.variable} ${almendra.variable}
        ${poppins.variable} ${playfair.variable} ${raleway.variable}
        ${lora.variable} ${montserrat.variable} ${inter.variable}
        ${dmserif.variable} ${manrope.variable} ${outfit.variable} ${merriweather.variable}
        antialiased
      `}>
        <Navbar/>
        {children}
        {/* whatsapp  */}
              <a
              href="https://wa.me/94752233855" // Replace with your WhatsApp number (e.g., 9477xxxxxxx)
              target="_blank"
              rel="noopener noreferrer"
              className="fixed bottom-6 right-6 z-50 bg-green-500  text-white rounded-full   p-4 shadow-lg transition-all duration-300"
              aria-label="Chat on WhatsApp"
            >
              <FaWhatsapp className="w-6 h-6" />
            </a>
            <a
              href="/components/request" // Replace with your WhatsApp number (e.g., 9477xxxxxxx)
              target="_blank"
              rel="noopener noreferrer"
              className="fixed bottom-6 left-6 z-50 bg-blue-500  text-white rounded-r-full p-2 py-3 shadow-lg transition-all duration-300"
              aria-label="Chat on WhatsApp"
            >
              Book Now
            </a>
        <Footer/>
      </body>
    </html>
  );
}
